tasks/force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

tasks/force-app/main/default/objects/Movie__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

tasks/force-app/main/default/objects/Movie__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genre</valueSetName>
    </valueSet>
</CustomField>

tasks/force-app/main/default/objects/Movie__c/fields/LegacyId__c.field-meta.xml
<CustomField>
    <fullName>LegacyId__c</fullName>
    <label>LegacyId</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

tasks/force-app/main/default/objects/Movie__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Script</label>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Movies</relationshipLabel>
    <relationshipName>Movies</relationshipName>
    <type>Lookup</type>
</CustomField>

tasks/force-app/main/default/objects/Movie__c/fields/TMDB_ID__c.field-meta.xml
<CustomField>
    <fullName>TMDB_ID__c</fullName>
    <label>TMDB_ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

tasks/force-app/main/default/objects/Script__c/Script__c.object-meta.xml
<CustomObject>
    <label>Script</label>
    <nameField>
        <label>Script Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

tasks/force-app/main/default/objects/Script__c/fields/LegacyId__c.field-meta.xml
<CustomField>
    <fullName>LegacyId__c</fullName>
    <label>LegacyId</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

tasks/force-app/main/default/objects/Script__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>Scripts</relationshipLabel>
    <relationshipName>Scripts</relationshipName>
    <type>Lookup</type>
</CustomField>

tasks/force-app/main/default/globalValueSets/Genre.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Action</fullName>
    </customValue>
    <customValue>
        <fullName>Adventure</fullName>
    </customValue>
    <customValue>
        <fullName>Animation</fullName>
    </customValue>
    <customValue>
        <fullName>Comedy</fullName>
    </customValue>
    <customValue>
        <fullName>Crime</fullName>
    </customValue>
    <customValue>
        <fullName>Drama</fullName>
    </customValue>
    <customValue>
        <fullName>Family</fullName>
    </customValue>
    <customValue>
        <fullName>Fantasy</fullName>
    </customValue>
    <customValue>
        <fullName>History</fullName>
    </customValue>
    <customValue>
        <fullName>Horror</fullName>
    </customValue>
    <customValue>
        <fullName>Mystery</fullName>
    </customValue>
    <customValue>
        <fullName>Romance</fullName>
    </customValue>
    <customValue>
        <fullName>Science_Fiction</fullName>
        <label>Science Fiction</label>
    </customValue>
    <customValue>
        <fullName>Thriller</fullName>
    </customValue>
    <customValue>
        <fullName>War</fullName>
    </customValue>
    <customValue>
        <fullName>Western</fullName>
    </customValue>
    <customValue>
        <fullName>Music</fullName>
    </customValue>
    <customValue>
        <fullName>Documentary</fullName>
    </customValue>
    <customValue>
        <fullName>Foreign</fullName>
    </customValue>
    <customValue>
        <fullName>TV_Movie</fullName>
        <label>TV Movie</label>
    </customValue>
    <customValue>
        <fullName>No_Genre</fullName>
        <label>No Genre</label>
    </customValue>
    <customValue>
        <fullName>[]</fullName>
        <isActive>false</isActive>
        <label>[]</label>
    </customValue>
    <masterLabel>Genre</masterLabel>
</GlobalValueSet>

tasks/themoviedb/classes/MovieDataImporter.cls
public class MovieDataImporter {

    public class MovieWrapper {
        public String id;
        public String name;
        public String tmdb_id;
        public String genre;
        public Decimal rating;
        public Decimal budget;
        public Decimal revenue;
        public ScriptWrapper script;
        public String release_date;
        public String status;
    }

    public class ScriptWrapper {
        public String id;
        public String name;
        public String description;
    }

    public static void importMovies(String jsonMovies) {
        
        List<MovieWrapper> movies = (List<MovieWrapper>) JSON.deserialize(jsonMovies, List<MovieWrapper>.class);

        for (MovieWrapper movieData : movies) {
            
            System.debug('Checking for TMDB ID: ' + movieData.tmdb_id);

            
            String tmdbId = movieData.tmdb_id != null ? movieData.tmdb_id.trim() : null;

            
            List<Movie__c> existingMovies = [SELECT Id, TMDB_ID__c FROM Movie__c WHERE TMDB_ID__c = :tmdbId LIMIT 1];
            System.debug('Query result for TMDB ID ' + tmdbId + ': ' + existingMovies);

            if (!existingMovies.isEmpty()) {
                System.debug('Movie with TMDB ID ' + tmdbId + ' already exists. Skipping import.');
                continue;
            }

            
            Script__c scriptRecord;
            if (movieData.script != null) {
                List<Script__c> existingScripts = [SELECT Id FROM Script__c WHERE LegacyId__c = :movieData.script.id LIMIT 1];
                if (!existingScripts.isEmpty()) {
                    scriptRecord = existingScripts[0];
                } else {
                    scriptRecord = new Script__c();
                    scriptRecord.LegacyId__c = movieData.script.id;
                    scriptRecord.Title__c = movieData.script.name;
                    scriptRecord.Description__c = movieData.script.description;
                    insert scriptRecord;
                }
            }

           
            Movie__c newMovie = new Movie__c();
            newMovie.LegacyId__c = movieData.id;
            newMovie.Title__c = movieData.name;
            newMovie.TMDB_ID__c = tmdbId;
            newMovie.Genre__c = movieData.genre;
            newMovie.Rating__c = movieData.rating;
            newMovie.Budget__c = movieData.budget;
            newMovie.Revenue__c = movieData.revenue;
            newMovie.Description__c = movieData.script != null ? movieData.script.description : null;

            
            if (scriptRecord != null) {
                newMovie.Script__c = scriptRecord.Id;
            }

            insert newMovie;
            System.debug('Imported movie: ' + newMovie.Title__c + ' with TMDB ID: ' + newMovie.TMDB_ID__c);
        }
    }
}


// For test
// String jsonMovies = '[{ "id": "1", "name": "Avatar", "tmdb_id": "19995", "genre": "Action;Adventure;Fantasy;Science_Fiction", "rating": 7.2, "budget": 237000000, "revenue": 2787965087, "script": { "id": "1", "name": "Avatar", "description": "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization." }, "release_date": "10/12/2009", "status": "Released" }, { "id": "2", "name": "Pirates of the Caribbean: At World\'s End", "tmdb_id": "285", "genre": "Adventure;Fantasy;Action", "rating": 6.9, "budget": 300000000, "revenue": 961000000, "script": { "id": "2", "name": "Pirates of the Caribbean: At World\'s End", "description": "Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems." }, "release_date": "19/05/2007", "status": "Released" }]';
// MovieDataImporter.importMovies(jsonMovies);